App:
  env: "development"
  logLevel: "info"
  corsAllowedOrigins:
    - "https://reprovingly-flying-chimp.cloudpub.ru"
    - "https://comically-integrated-silkworm.cloudpub.ru"
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
    - "http://localhost:4173"
    - "http://127.0.0.1:4173"

Server:
  appVersion: "0.1.0"
  host: "0.0.0.0"
  port: "8080"

Database:
  port: 5432
  host: localhost
  user: tracker
  password: tracker
  DBName: tracker
  sslMode: disable
#  url: "postgres://tracker:tracker@localhost:5432/tracker?sslmode=disable"

Telegram:
  botToken: "7741755347:AAHkxoL83tQQuf3IOIcUfGEuk8NWU50LDxE"
  webhookSecret: "7741755347:AAHkxoL83tQQuf3IOIcUfGEuk8NWU50LDxE"

Auth:
  accessSecret: "7741755347:AAHkxoL83tQQuf3IOIcUfGEuk8NWU50LDxE"
  refreshSecret: "7741755347:AAHkxoL83tQQuf3IOIcUfGEuk8NWU50LDxE"
