-- +goose Up
ALTER TABLE workouts
  ADD COLUMN IF NOT EXISTS sets INT NOT NULL DEFAULT 1 CHECK (sets > 0),
  ADD COLUMN IF NOT EXISTS reps INT NOT NULL DEFAULT 1 CHECK (reps > 0),
  ADD COLUMN IF NOT EXISTS weight_kg NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (weight_kg >= 0);

-- +goose Down
ALTER TABLE workouts
  DROP COLUMN IF EXISTS weight_kg,
  DROP COLUMN IF EXISTS reps,
  DROP COLUMN IF EXISTS sets;
